# Generated by Django 5.1.3 on 2024-11-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog',
         '0002_alter_newspaper_options_alter_redactor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={},
        ),
        migrations.AlterModelOptions(
            name='redactor',
            options={
                'verbose_name': 'redactor',
                'verbose_name_plural': 'redactors',
            },
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(
                default='Untitled',
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='redactor',
            field=models.ManyToManyField(
                related_name='newspaper',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='topic',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='newspaper',
                to='catalog.topic',
            ),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ActivateToken',
        ),
    ]
